export const GET_USERDATA_SUCCESS = 'GET_USERDATA_SUCCESS';
export const CHECK_SAVED_THEME = 'CHECKTHEME';
export const TOGGLE_THEME = 'TOGGLE_THEME';
export const SEARCH_GITHUB_USER_ASYNC_START = 'SEARCH_GITHUB_USER_ASYNC_START';
export const SEARCH_GITHUB_USER_ASYNC_END = 'SEARCH_GITHUB_USER_ASYNC_END';
export const SEARCH_GITHUB_USER_ASYNC_ERROR = 'SEARCH_GITHUB_USER_ASYNC_ERROR';
export const GET_SYSTEM_THEME = 'GET_SYSTEM_THEME';
